app/models.py
from datetime import datetime, timezone
from typing import Optional
import sqlalchemy as sa
import sqlalchemy.orm as so
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


#
# The crew class holds information for a crew, or small groups of user.
# A crew has a derived attribute which is the collective 'power' of all its members
#
class Crew(db.Model):
    crew_id: so.Mapped[int] = so.mapped_column(primary_key=True)
    crew_name: so.Mapped[str] = so.mapped_column(sa.String(64), index=True, unique=True)
    creation_date: so.Mapped[Optional[datetime]] = so.mapped_column(default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return '<Crew {}>'.format(self.crew_name)


#
# UserMixin is an implementation of users of flask-login
#
class User(UserMixin, db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    username: so.Mapped[str] = so.mapped_column(sa.String(64), index=True, unique=True)
    email: so.Mapped[str] = so.mapped_column(sa.String(120), index=True, unique=True)
    password_hash: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256))
    power: so.Mapped[int] = so.mapped_column(sa.Integer, default=0)
    crew_user_id: so.Mapped[int] = so.mapped_column(sa.ForeignKey(Crew.crew_id), nullable=True)

    posts: so.WriteOnlyMapped['Post'] = so.relationship(
        back_populates='author')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


# The loader function helps to connect flask-login with the database
@login.user_loader
def load_user(login_user_id):
    return db.session.get(User, int(login_user_id))


class Post(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    body: so.Mapped[str] = so.mapped_column(sa.String(64))
    user_id: so.Mapped[int] = so.mapped_column(sa.ForeignKey(User.id), index=True)
    timestamp: so.Mapped[datetime] = so.mapped_column(index=True, default=lambda: datetime.now(timezone.utc))

    author: so.Mapped[User] = so.relationship(back_populates='posts')

    def __repr__(self):
        return '<Post {}>'.format(self.body)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    post = TextAreaField('Message', validators=[DataRequired()])
    submit = SubmitField('Send')


class CrewForm(FlaskForm):
    crew_name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Create')


class EnrollForm(FlaskForm):
    crew_name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Enroll')

app/__init__.py
from flask import Flask
from app.config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)
# This tells flask login which function handles the login, the name is the same one would use in a url_for()
login.login_view = 'login'
moment = Moment(app)

from app.errors import bp as errors_bp
app.register_blueprint(errors_bp)

from app.auth import bp as auth_bp
app.register_blueprint(auth_bp)

from app.main import bp as main_bp
app.register_blueprint(main_bp)

# Keep import at bottom to avoid circular dependencies
from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

# Keep import at bottom to avoid circular dependencies
from app.main import routes

app/main/routes.py
import random
from flask import render_template, redirect, url_for
from flask_login import current_user, login_required
import sqlalchemy as sa
from app import db
from app.main import bp
from app.models import User, Post, Crew
from app.main.forms import PostForm, CrewForm, EnrollForm


@bp.route('/')
@bp.route('/index')
def index():
    if current_user.is_authenticated:
        return redirect((url_for('main.home')))
    return render_template('index.html')


@bp.route('/home')
@login_required
def home():
    return render_template('home.html', user=current_user)


@bp.route('/user/<username>')
@login_required
def user(username):
    user = db.first_or_404(sa.select(User).where(User.username == username))
    return render_template('user.html', user=user)


@bp.route('/soon')
@login_required
def soon():
    return render_template('errors/coming-soon.html')


@bp.route('/play')
@login_required
def play():
    return render_template('play.html')


@bp.route('/add_coins/<username>')
def add_coins(username):
    user = db.first_or_404(sa.select(User).where(User.username == username))
    coins = random.randint(0, 500)
    user.power += coins
    db.session.commit()
    return render_template('play.html', coins=coins)


@bp.route('/crew')
@login_required
def crew():
    crew_id = current_user.crew_user_id
    if crew_id is None:
        return redirect(url_for('main.create_crew'))
    crew = db.first_or_404(sa.select(Crew).where(Crew.crew_id == crew_id))
    crewmates = db.session.scalars(sa.select(User).where(User.crew_user_id == crew_id).order_by(User.power))
    wealth = 0
    for crewmate in crewmates:
        wealth += crewmate.power

    return render_template('crew.html', crew=crew, wealth=wealth)


@bp.route('/create_crew', methods=['GET', 'POST'])
@login_required
def create_crew():
    crew_form = CrewForm()
    if crew_form.validate_on_submit():
        name = crew_form.crew_name.data
        crew = Crew(crew_name=name)
        db.session.add(crew)
        db.session.commit()
        return redirect(url_for('main.enroll', crew_name=name))

    return render_template('crewless.html', crew_form=crew_form)


@bp.route('/enroll/', methods=['GET', 'POST'])
@login_required
def enroll():
    enroll_form = EnrollForm()
    if enroll_form.validate_on_submit():
        crew_id = db.session.scalar(sa.select(Crew).where(Crew.crew_name == enroll_form.crew_name.data)).crew_id
        current_user.crew_user_id = crew_id
        db.session.commit()
        return redirect(url_for('main.crew'))
    return render_template('enroll.html', enroll_form=enroll_form)


@bp.route('/inbox')
@login_required
def inbox():
    query = sa.select(Post).order_by(Post.timestamp.desc())
    posts = db.session.scalars(query)
    return render_template('inbox.html', posts=posts)


@bp.route('/send_message', methods=['GET', 'POST'])
@login_required
def send_message():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.post.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.inbox'))
    return render_template('send-message.html', form=form)


@bp.route('/leaderboard')
@login_required
def leaderboard():
    query = sa.select(User).order_by(User.power.desc())
    users = db.session.scalars(query)
    return render_template('leaderboard.html', users=users)

app/templates/_header.html
<header class="header">

  <div class="header__left">
    <button class="header__menu">
      <img class="header__menu__icon" src="{{ url_for('static',filename='assets/icons/burger-menu-left.svg') }}">
    </button>

    <div class="header__title">Calarium</div>
  </div>

  <button class="planet hide-on-mobile">
    <a href="{{ url_for('main.home') }}">
      <img class="planet__icon" src="{{ url_for('static',filename='assets/icons/saturn.svg') }}">
    </a>
    <span class="planet__text">explore.</span>
  </button>

  <div class="header__right">

    <input type="checkbox" id="header__sound" checked>
    <label for="header__sound">
      <img class="header__sound__icon" src="{{ url_for('static', filename='assets/icons/sound.svg') }}">
    </label>

    <a href="{{ url_for('main.user', username=current_user.username) }}">
    <button class="header__user">
      <img class="header__user__icon" src="{{ url_for('static',filename='assets/icons/user.svg') }}">
    </button>
    </a>
  </div>

</header>

app/templates/_lb-user.html
<a href="{{ url_for('main.user', username=user.username) }}">
  <div class="leaderboard__users__view">
    <p>{{ user.username }}</p>
    <p class="score">{{ user.power }}</p>
  </div>
</a>

app/templates/_music.html
  <audio id="audio_track" loop>
    <source src="{{ url_for('static',filename='assets/sound/main-theme.mp3') }}" type="audio/mpeg">
  </audio>

app/templates/_navigator.html
<nav class="navigator mobile-fix">

  <a href="{{ url_for('main.play') }}">
    <button class="navigator__circle">
      <img class="navigator__circle__icon" src="{{ url_for('static',filename='assets/icons/rocket.svg') }}">
    </button>
  </a>
  <a href="{{ url_for('main.crew') }}">
    <button class="navigator__circle">
      <img class="navigator__circle__icon" src="{{ url_for('static',filename='assets/icons/crew.svg') }}">
    </button>
  </a>

  <a href="{{ url_for('main.inbox') }}">
    <button class="navigator__circle">
      <img class="navigator__circle__icon" src="{{ url_for('static',filename='assets/icons/chat.svg') }}">
    </button>
  </a>

  <a href="{{ url_for('main.leaderboard') }}">
    <button class="navigator__circle">
      <img class="navigator__circle__icon" src="{{ url_for('static',filename='assets/icons/leaderboard.svg') }}">
    </button>
  </a>

  <div class="separator hide-on-mobile"></div>


    <button class="navigator__options hide-on-mobile js-options-button">
      <img class="navigator__options__icon" src="{{ url_for('static',filename='assets/icons/settings.svg') }}">
      <span class="navigator__options__text">settings</span>
    </button>

  <a href="{{ url_for('auth.logout') }}">
  <button class="navigator__options navigator__options__logout hide-on-mobile">
    <img class="navigator__options__icon" src="{{ url_for('static',filename='assets/icons/logout.svg') }}">
    <span class="navigator__options__text">logout</span>
  </button>
  </a>

</nav>

app/templates/_three.html
<canvas class="three-background"></canvas>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Calarium</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- FONTS: Inter regular, bold, extra bold -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;800&display=swap" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/style.css') }}">
  <link rel="manifest" href="{{ url_for('static', filename='pwa/manifest.json') }}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script type="importmap">
    {
      "imports": {
        "three": "https://unpkg.com/three@0.159.0/build/three.module.js",
        "three/addons/": "https://unpkg.com/three@0.159.0/examples/jsm/"
      }
    }
  </script>
  <script type="module" defer src="{{ url_for('static',filename='main.js') }}"></script>
  <script type="module" defer src="{{ url_for('static',filename='background.js') }}"></script>
</head>
<body>

<main>
  {% block background %}{% endblock %}

  {% block main_content %}{% endblock %}
</main>

{% block navigator %}{% endblock %}

{% block header %}{% endblock %}

</body>
</html>

app/templates/crew.html
{% extends "base.html" %}

{% block main_content %}
<div class="guild">
  <p class="guild__name">{{ crew.crew_name }}</p>
  <p class="guild__title">Total crew wealth: {{ wealth }} starcoins</p>
</div>
{% endblock %}


{% block navigator %}
{% include '_navigator.html' %}
{% endblock %}


{% block header %}
{% include '_header.html' %}
{% endblock %}

{% include '_music.html' %}

app/templates/crewless.html
{% extends "base.html" %}

{% block main_content %}
<div class="page-content">
    <div class="login-title">No crew?</div>
    <form class="form" action="" method="post" novalidate>
        {{ crew_form.hidden_tag() }}
        {{ crew_form.crew_name(size=32, class_="input-field", placeholder_="Crew name") }}
        {{ crew_form.submit(class_="button") }}
    </form>

    <div class="login-title">Looking for an already existing one?</div>
    <a href="{{ url_for('main.enroll') }}">
        <button class="button">Enroll</button>
    </a>
</div>
{% endblock %}


{% block navigator %}
{% include '_navigator.html' %}
{% endblock %}


{% block header %}
{% include '_header.html' %}
{% endblock %}

{% include '_music.html' %}

app/templates/enroll.html
{% extends "base.html" %}

{% block main_content %}
<div class="page-content">
    <div class="login-title">No crew?</div>
    <form class="form" action="" method="post" novalidate>
        {{ enroll_form.hidden_tag() }}
        {{ enroll_form.crew_name(size=32, class_="input-field", placeholder_="Crew name") }}
        {{ enroll_form.submit(class_="button") }}
    </form>
</div>
{% endblock %}


{% block navigator %}
{% include '_navigator.html' %}
{% endblock %}


{% block header %}
{% include '_header.html' %}
{% endblock %}

{% include '_music.html' %}

app/templates/home.html
{% extends "base.html" %}

{% block background %}
{% include '_three.html' %}
{% endblock %}

{% block main_content %}
<div class="page-content">
    <div class="page-content-insert">
        <div class="page-text">Get ready for your journey, {{ user.username }}</div>
    </div>
    <div class="button-container">
      <button class="button js-download">
        download
      </button>
      <button class="button button__mobile js-new-chat">
        new chat
      </button>
    </div>
</div>
{% endblock %}


{% block navigator %}
{% include '_navigator.html' %}
{% endblock %}


{% block header %}
{% include '_header.html' %}
{% endblock %}

{% include '_music.html' %}

app/templates/index.html
{% extends "base.html" %}

{% block background %}
{% include '_three.html' %}
{% endblock %}

{% block main_content %}
<div class="page-content">
    <div class="page-text">
      Calarium
    </div>
    <div class="button-container">
      <a href="{{ url_for('auth.login') }}">
      <button class="button button__mobile js-new-chat">
        login
      </button>
      </a>

      <a href="{{ url_for('auth.register') }}">
      <button class="button js-download">
        sign-up
      </button>
      </a>
    </div>
  </div>
{% endblock %}


{% block navigator %}
<nav class="navigator hide-on-desktop">
  <button class="planet hide-on-desktop">
    <img class="planet__icon hide-on-desktop" src="{{ url_for('static',filename='assets/icons/saturn.svg') }}">
    <span class="planet__text hide-on-desktop">explore.</span>
  </button>
</nav>
{% endblock %}


{% block header %}
<header class="header">

  <div class="header__left">
    <button class="planet">
      <img class="planet__icon" src="{{ url_for('static',filename='assets/icons/saturn.svg') }}">
    </button>
  </div>

  <div class="header__right">

    <input type="checkbox" id="header__sound" checked>
    <label for="header__sound">
      <img class="header__sound__icon" src="{{ url_for('static',filename='assets/icons/sound.svg') }}">
    </label>

    <a href="{{ url_for('auth.login') }}">
    <div class="rect-button-container js-login-button">
      <button class="button rectangle-button"></button>
      <span class="login">login</span>
    </div>
    </a>

    <button class="header__user js-user-icon">
      <img class="header__user__icon" src="{{ url_for('static',filename='assets/icons/user.svg') }}">
    </button>

  </div>

</header>
{% endblock %}

{% include '_music.html' %}

app/templates/play.html
{% extends "base.html" %}

{% block background %}
{% include '_three.html' %}
{% endblock %}

{% block main_content %}
  <div class="page-content">
    <a href="{{ url_for('main.add_coins', username=current_user.username) }}">
    <button class="button">play</button>
    </a>
    {% if coins is not none %}
    <p id="game-coin-notification">You gained {{ coins }} starcoins!</p>
    {% endif %}
  </div>
{% endblock %}

{% block navigator %}
{% include '_navigator.html' %}
{% endblock %}


{% block header %}
{% include '_header.html' %}
{% endblock %}

{% include '_music.html' %}

app/templates/register.html
{% extends "base.html" %}

{% block background %}
{% include '_three.html' %}
{% endblock %}

{% block main_content %}
<div class="page-content">
    <div class="login-title">Calarium</div>
    <form class="form" action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        {{ form.username(size=32, class_="input-field", placeholder_="username") }}
        {{ form.email(size=64, class_="input-field", placeholder_="email") }}
        {{ form.password(size=32, class_="input-field", placeholder_="password") }}
        {{ form.password2(size=32, class_="input-field", placeholder_="repeat password") }}
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        {{ form.submit(class_="button") }}
    </form>
</div>
{% endblock %}

{% include '_music.html' %}

app/templates/user.html
{% extends "base.html" %}

{% block main_content %}
<div class="page-content">
    <div class="page-content-insert">
        <div class="login-title">
        {% if user == current_user %}
            Welcome to your profile, {{ user.username }}
        {% else %}
            <a href="{{ url_for('main.play') }}">
                <p>Want to embark on a journey alongside {{ user.username }}?</p>
            </a>
        {% endif %}
        </div>
    </div>
    {% if user == current_user %}
    <a href="{{ url_for('main.play') }}">
        <button class="button">Game</button>
    </a>
    <a href="{{ url_for('main.crew') }}">
        <button class="button">Crew</button>
    </a>
    <a href="{{ url_for('main.inbox') }}">
        <button class="button">Inbox</button>
    </a>
    <a href="{{ url_for('main.leaderboard') }}">
        <button class="button">Leaderboard</button>
    </a>
    {% endif %}
</div>
{% endblock %}

{% block header %}
{% include '_header.html' %}
{% endblock %}

{% include '_music.html' %}